/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Currency = bigint;
export interface FantasyTeam {
  'id' : TeamId,
  'playerIds' : Array<PlayerId>,
  'balance' : Currency,
  'owner' : Principal,
  'name' : string,
  'totalPoints' : Points,
}
export interface Player {
  'id' : PlayerId,
  'name' : string,
  'role' : Role,
  'team' : string,
  'totalPoints' : Points,
  'baseCost' : Currency,
}
export type PlayerId = bigint;
export type Points = bigint;
export type Role = { 'keeper' : null } |
  { 'allRounder' : null } |
  { 'bowler' : null } |
  { 'batsman' : null };
export type TeamId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[string, Role, string, Currency], PlayerId>,
  'addPlayerToTeam' : ActorMethod<[TeamId, PlayerId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFantasyTeam' : ActorMethod<[string], TeamId>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllTeamsSortedByName' : ActorMethod<[], Array<FantasyTeam>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayer' : ActorMethod<[PlayerId], Player>,
  'getTeam' : ActorMethod<[TeamId], FantasyTeam>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTeams' : ActorMethod<[Principal], Array<FantasyTeam>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateTeam' : ActorMethod<[TeamId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];