/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({
  'keeper' : IDL.Null,
  'allRounder' : IDL.Null,
  'bowler' : IDL.Null,
  'batsman' : IDL.Null,
});
export const Currency = IDL.Nat;
export const PlayerId = IDL.Nat;
export const TeamId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Points = IDL.Nat;
export const Player = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'role' : Role,
  'team' : IDL.Text,
  'totalPoints' : Points,
  'baseCost' : Currency,
});
export const FantasyTeam = IDL.Record({
  'id' : TeamId,
  'playerIds' : IDL.Vec(PlayerId),
  'balance' : Currency,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'totalPoints' : Points,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([IDL.Text, Role, IDL.Text, Currency], [PlayerId], []),
  'addPlayerToTeam' : IDL.Func([TeamId, PlayerId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFantasyTeam' : IDL.Func([IDL.Text], [TeamId], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeamsSortedByName' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
  'getTeam' : IDL.Func([TeamId], [FantasyTeam], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTeams' : IDL.Func([IDL.Principal], [IDL.Vec(FantasyTeam)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'validateTeam' : IDL.Func([TeamId], [], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({
    'keeper' : IDL.Null,
    'allRounder' : IDL.Null,
    'bowler' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const Currency = IDL.Nat;
  const PlayerId = IDL.Nat;
  const TeamId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Points = IDL.Nat;
  const Player = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'role' : Role,
    'team' : IDL.Text,
    'totalPoints' : Points,
    'baseCost' : Currency,
  });
  const FantasyTeam = IDL.Record({
    'id' : TeamId,
    'playerIds' : IDL.Vec(PlayerId),
    'balance' : Currency,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'totalPoints' : Points,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [IDL.Text, Role, IDL.Text, Currency],
        [PlayerId],
        [],
      ),
    'addPlayerToTeam' : IDL.Func([TeamId, PlayerId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFantasyTeam' : IDL.Func([IDL.Text], [TeamId], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeamsSortedByName' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
    'getTeam' : IDL.Func([TeamId], [FantasyTeam], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTeams' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FantasyTeam)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'validateTeam' : IDL.Func([TeamId], [], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };